[package]
name = "vow-cli"
description = "The vow command line tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "vow"
path = "src/main.rs"

[dependencies]
vow-diagnostics = { path = "../vow-diagnostics" }
vow-driver = { path = "../vow-driver" }
vow-interp = { path = "../vow-interp" }
vow-typeck = { path = "../vow-typeck" }

[lints]
workspace = true
