[package]
name = "deed-typeck"
description = "Gives every Deed expression a type"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
deed-ast.workspace = true
deed-diagnostics.workspace = true
deed-resolve.workspace = true

[dev-dependencies]
deed-lexer.workspace = true
deed-parser.workspace = true

[lints]
workspace = true
