[package]
name = "deed-codegen"
description = "Compiles deed-mir to WebAssembly, and runs the result"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
deed-diagnostics = { path = "../deed-diagnostics" }
deed-mir = { path = "../deed-mir" }

[lints]
workspace = true
