[package]
name = "deed-dap"
description = "A debug adapter for Deed"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
deed-diagnostics.workspace = true
deed-driver.workspace = true
deed-interp.workspace = true
deed-lsp.workspace = true
deed-rt.workspace = true

[lints]
workspace = true
