[package]
name = "deed-ast"
description = "Syntax tree for the Deed language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
deed-diagnostics = { path = "../deed-diagnostics" }

[lints]
workspace = true
