[package]
name = "vow-lsp"
description = "A language server for Vow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
vow-ast = { path = "../vow-ast" }
vow-diagnostics = { path = "../vow-diagnostics" }
vow-driver = { path = "../vow-driver" }
vow-fmt = { path = "../vow-fmt" }
vow-lexer = { path = "../vow-lexer" }
vow-parser = { path = "../vow-parser" }
vow-resolve = { path = "../vow-resolve" }

[lints]
workspace = true
