[package]
name = "vow-lsp"
description = "A language server for Vow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
vow-diagnostics = { path = "../vow-diagnostics" }
vow-driver = { path = "../vow-driver" }

[lints]
workspace = true
