//! The generator behind `crates/deed-explain/generated/pages.rs`.
//!
//! It lives here, and not beside the pages, because of what it has to decide.
//! A page's example claims to be a program that produces that code, and the
//! only thing that can settle that claim is the compiler. `deed-explain`
//! deliberately depends on nothing — it is data — and making it depend on the
//! compiler to test itself would put two published crates in a dependency
//! cycle, which `cargo publish` cannot order. So the generator sits on the
//! side that already has a checker.
//!
//! Nothing here is invented. The reasoning is the `///` lines already above
//! each `pub const` in a `codes.rs`; the example is lifted from a test that
//! `crates/deed-driver/tests/codes.rs` already requires to exist, and is kept
//! only if running it produces the code.
//!
//! - `the_generated_pages_are_the_ones_this_tree_would_produce` fails when the
//!   committed file has drifted.
//! - `every_example_produces_the_code_its_page_is_about` reads the committed
//!   file rather than the tree, so it holds the shipped pages even if the
//!   generator is never run again.
//! - `regenerate_the_pages` (`--ignored`) writes it.

use std::fs;
use std::path::{Path, PathBuf};

use deed_diagnostics::SourceMap;
use deed_driver::{check_text, program_of};
use deed_interp::run_tests;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("the workspace root should be two directories up")
        .to_path_buf()
}

fn generated() -> PathBuf {
    root()
        .join("crates")
        .join("deed-explain")
        .join("generated")
        .join("pages.rs")
}

#[test]
fn the_generated_pages_are_the_ones_this_tree_would_produce() {
    let committed = fs::read_to_string(generated()).expect("generated/pages.rs should be there");
    assert_eq!(
        committed.replace("\r\n", "\n"),
        render(&root()),
        "generated/pages.rs has drifted from the `codes.rs` files it is made of. \
         Run: cargo test -p deed-driver --test explain_pages -- --ignored"
    );
}

/// The claim the `example` field makes, asked of the shipped pages.
///
/// The pages are read back rather than regenerated, because what a reader of
/// `deed explain` gets is the committed file. This is the test that was
/// missing: the example used to be the first deed-looking string in a test
/// mentioning the code, which is a different thing from a program that
/// produces it, and forty-five of the eighty-nine were not.
#[test]
fn every_example_produces_the_code_its_page_is_about() {
    let mut wrong = Vec::new();
    let mut checked = 0;

    for page in deed_explain::all_pages() {
        let Some(example) = page.example else {
            continue;
        };
        checked += 1;
        if !produces(page.code, example) {
            wrong.push(format!("{} ({})", page.code, page.name));
        }
    }

    assert!(
        checked > 50,
        "only {checked} pages carry an example, so this measured almost nothing"
    );
    assert!(
        wrong.is_empty(),
        "these pages show a program that does not produce the code they explain: {}",
        wrong.join(", ")
    );
}

#[test]
#[ignore = "writes a file; run it on purpose"]
fn regenerate_the_pages() {
    fs::write(generated(), render(&root())).expect("should write generated/pages.rs");
}

/// Whether checking, and then running, this snippet reports this code.
fn produces(code: &str, snippet: &str) -> bool {
    let mut sources = SourceMap::new();
    let checked = check_text(&mut sources, "example.deed", snippet);

    if checked.diagnostics.iter().any(|d| d.code == code) {
        return true;
    }

    // A contract failure is a code too, and it only appears when the program
    // runs. Only for a file that checks: running one that does not would be
    // measuring the wrong thing, and the compiler refuses it anyway.
    if checked.has_errors() {
        return false;
    }

    let checks = [checked];
    let file = checks[0].file;
    let program = program_of(&checks);
    run_tests(&program, file)
        .iter()
        .filter_map(|outcome| outcome.failure.as_ref())
        .any(|failure| failure.code == code)
}

/// The whole of the generated file, as text.
fn render(root: &Path) -> String {
    let codes = declared_codes(root);
    assert!(
        codes.len() > 50,
        "only {} codes were found, so something did not read the tree",
        codes.len()
    );
    let test_text = test_corpus(root);

    let mut output = String::new();
    output.push_str(
        "// @generated by `cargo test -p deed-driver --test explain_pages -- --ignored`.\n",
    );
    output.push_str("// The reasoning comes from the doc comments above each `pub const` in a\n");
    output.push_str("// `codes.rs`; the example comes from a test that already had to exist.\n");
    output.push_str("// Edit those, not this.\n\n");
    output.push_str("pub static PAGES: &[Page] = &[\n");

    for (name, code, doc) in &codes {
        let (example, example_source) = find_example(&test_text, name, code);
        output.push_str("    Page {\n");
        output.push_str(&format!("        code: {code:?},\n"));
        output.push_str(&format!("        name: {name:?},\n"));
        output.push_str(&format!("        text: {doc:?},\n"));
        match example {
            Some(ex) => {
                output.push_str(&format!("        example: Some({ex:?}),\n"));
                output.push_str(&format!(
                    "        example_source: Some({:?}),\n",
                    example_source.unwrap_or_default()
                ));
            }
            None => {
                output.push_str("        example: None,\n");
                output.push_str("        example_source: None,\n");
            }
        }
        output.push_str("    },\n");
    }

    output.push_str("];\n");
    output
}

/// All `pub const NAME: &str = "DEEDnnnn"` entries across the workspace,
/// together with the `///` doc-comment lines that immediately precede them.
fn declared_codes(root: &Path) -> Vec<(String, String, String)> {
    let mut codes = Vec::new();

    let mut crate_dirs: Vec<PathBuf> = fs::read_dir(root.join("crates"))
        .expect("crates/ should exist")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    crate_dirs.sort();

    for krate in crate_dirs {
        let path = krate.join("src").join("codes.rs");
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };

        let mut doc_lines: Vec<String> = Vec::new();
        for line in text.lines() {
            let trimmed = line.trim();

            if let Some(rest) = trimmed.strip_prefix("///") {
                let content = rest.strip_prefix(' ').unwrap_or(rest);
                doc_lines.push(content.to_string());
            } else if let Some(rest) = trimmed.strip_prefix("pub const ") {
                if let Some((name, rest)) = rest.split_once(':') {
                    if let Some(start) = rest.find("\"DEED") {
                        if let Some(end) = rest[start + 1..].find('"') {
                            let code = rest[start + 1..start + 1 + end].to_string();
                            let doc = doc_lines.join("\n");
                            codes.push((name.trim().to_string(), code, doc));
                        }
                    }
                }
                doc_lines.clear();
            } else if !trimmed.is_empty() && !trimmed.starts_with("//") {
                doc_lines.clear();
            }
        }
    }

    codes
}

/// All test source text in the workspace, with its path, so examples can be
/// traced back to the file they came from.
fn test_corpus(root: &Path) -> Vec<(String, String)> {
    let mut corpus = Vec::new();
    let crates_dir = root.join("crates");

    if let Ok(entries) = fs::read_dir(&crates_dir) {
        let mut dirs: Vec<PathBuf> = entries
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for krate in dirs {
            collect_test_files(&krate.join("tests"), root, &mut corpus);
        }
    }
    corpus
}

fn collect_test_files(dir: &Path, root: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.flatten().map(|entry| entry.path()).collect();
    // Sorted, or the pages depend on what order the filesystem hands them back
    // and the freshness check above becomes a coin toss.
    paths.sort();
    for path in paths {
        if path.is_dir() {
            collect_test_files(&path, root, out);
        } else if path.extension().is_some_and(|e| e == "rs")
            && path.file_name().is_some_and(|n| n != "codes.rs")
        {
            if let Ok(text) = fs::read_to_string(&path) {
                let rel = path
                    .strip_prefix(root)
                    .map(|p| p.to_string_lossy().replace('\\', "/"))
                    .unwrap_or_else(|_| path.to_string_lossy().into_owned());
                out.push((rel, text));
            }
        }
    }
}

/// The example and its source path for a given code.
///
/// Every deed snippet in every test that names the code is a candidate, and
/// the first one that produces the code wins. The old rule took the first
/// candidate and asked nothing, which is how a page came to show the control
/// arm of a test, or one module of a two-module program.
fn find_example(
    corpus: &[(String, String)],
    name: &str,
    code: &str,
) -> (Option<String>, Option<String>) {
    for (path, text) in corpus {
        if !text.contains(name) && !text.contains(code) {
            continue;
        }

        for snippet in candidates(text, name, code) {
            if produces(code, &snippet) {
                return (Some(snippet), Some(path.clone()));
            }
        }
    }
    (None, None)
}

/// Every deed snippet inside a test that names `name` or `code`, in order.
fn candidates(text: &str, name: &str, code: &str) -> Vec<String> {
    let mut out = Vec::new();
    for (start, _) in text.match_indices("#[test]") {
        let body = test_body(text, start);
        if !body.contains(name) && !body.contains(code) {
            continue;
        }
        out.extend(deed_snippets(body));
    }
    out
}

/// One test function, from its attribute to its closing brace.
///
/// Stopping at the next `#[test]` instead swallows whatever introduces it, and
/// these files introduce a test with a banner naming its code. Every page whose
/// code was named that way was offered the previous test's program first.
fn test_body(text: &str, start: usize) -> &str {
    let bytes = text.as_bytes();
    let len = text.len();
    let mut i = start;
    let mut depth = 0usize;
    let mut open = false;

    while i < len {
        match bytes[i] {
            b'/' if i + 1 < len && bytes[i + 1] == b'/' => {
                while i < len && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            b'"' => {
                i += 1;
                while i < len {
                    match bytes[i] {
                        b'\\' => i += 2,
                        b'"' => {
                            i += 1;
                            break;
                        }
                        _ => i += 1,
                    }
                }
                continue;
            }
            // `'{'` and `'\''`, which would otherwise count as braces.
            b'\'' if i + 2 < len && (bytes[i + 2] == b'\'' || bytes[i + 1] == b'\\') => {
                i += 2;
                while i < len && bytes[i] != b'\'' {
                    i += 1;
                }
            }
            b'{' => {
                depth += 1;
                open = true;
            }
            b'}' => {
                depth -= 1;
                if open && depth == 0 {
                    return &text[start..=i];
                }
            }
            _ => {}
        }
        i += 1;
    }

    &text[start..]
}

/// Every deed-looking string literal in a block of Rust source, in order.
fn deed_snippets(body: &str) -> Vec<String> {
    // A `"..."` literal that spans a newline and carries a deed keyword.
    // Walked character by character rather than with a regex, because this
    // workspace has no dependencies.
    let deed_markers = [
        "fn ", "type ", "record ", "module ", "handler ", "let ", "for ", "effect ", "choice ",
    ];

    let mut found = Vec::new();
    let bytes = body.as_bytes();
    let len = body.len();
    let mut i = 0;

    while i < len {
        // Line comments, skipped so a string inside one is not found.
        if bytes[i] == b'/' && i + 1 < len && bytes[i + 1] == b'/' {
            while i < len && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }

        if bytes[i] != b'"' {
            i += 1;
            continue;
        }

        // #780: a `format!` argument is a template, not a program. Its
        // placeholders and doubled braces are Rust talking to `format!`, and a
        // page that prints them shows something no compiler would accept. The
        // literal is skipped rather than repaired.
        let is_template = ends_with_format_macro(&body[..i]);

        i += 1;
        let mut buf = String::new();
        let mut escaped = false;

        while i < len {
            let ch = bytes[i] as char;
            if escaped {
                match ch {
                    'n' => buf.push('\n'),
                    't' => buf.push('\t'),
                    'r' => buf.push('\r'),
                    '\\' => buf.push('\\'),
                    '"' => buf.push('"'),
                    'x' => {
                        i += 1;
                        if i + 1 < len {
                            i += 1;
                        }
                        buf.push(' ');
                    }
                    // A backslash before a newline is Rust joining two source
                    // lines: neither the newline nor the indentation after it
                    // is in the string.
                    '\n' => {
                        i += 1;
                        while i < len && (bytes[i] as char).is_whitespace() {
                            i += 1;
                        }
                        escaped = false;
                        continue;
                    }
                    '\r' => {
                        i += 1;
                        while i < len && (bytes[i] as char).is_whitespace() {
                            i += 1;
                        }
                        escaped = false;
                        continue;
                    }
                    _ => {
                        buf.push('\\');
                        buf.push(ch);
                    }
                }
                escaped = false;
                i += 1;
                continue;
            }
            match ch {
                '\\' => {
                    escaped = true;
                    i += 1;
                }
                '"' => {
                    i += 1;
                    break;
                }
                _ => {
                    buf.push(ch);
                    i += 1;
                }
            }
        }

        if is_template {
            continue;
        }

        if buf.contains('\n') && deed_markers.iter().any(|m| buf.contains(m)) {
            found.push(buf);
        }
    }

    found
}

/// Whether the text immediately before a string literal opens a `format!`-like
/// macro call, which makes that literal a template rather than a program.
fn ends_with_format_macro(before: &str) -> bool {
    let head = before.trim_end();
    let Some(head) = head.strip_suffix('(') else {
        return false;
    };
    let head = head.trim_end();
    // `format!`, `write!`, `writeln!`, `panic!`, `assert!` and the rest all
    // end the same way, and every one of them takes a template first.
    head.ends_with('!')
}

#[test]
fn a_test_body_ends_before_what_introduces_the_next_one() {
    let text = "\
#[test]
fn first() {
    only_error(\"module a\\n\\nfn f() -> Int {\\n  Int n = 1\\n}\\n\").under(codes::A);
}

// -- DEED2011, a range ------------------------------------------------------

/// Names the code that belongs to the test below it.
#[test]
fn second() {
    only_error(\"module a\\n\\nfn g() -> () {\\n  for i in 0..10 {\\n  }\\n}\\n\").under(codes::B);
}
";
    let first = test_body(text, text.find("#[test]").expect("a test"));
    assert!(first.contains("Int n = 1"), "{first}");
    assert!(
        !first.contains("DEED2011"),
        "the banner introducing the next test is not part of this one: {first}"
    );
}
