[package]
name = "deed-interp"
description = "Runs Deed programs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
deed-ast.workspace = true
deed-diagnostics.workspace = true
deed-resolve.workspace = true
deed-rt.workspace = true

[dev-dependencies]
deed-lexer.workspace = true
deed-parser.workspace = true

[lints]
workspace = true
