[package]
name = "vow-interp"
description = "Runs Vow programs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
vow-ast = { path = "../vow-ast" }
vow-diagnostics = { path = "../vow-diagnostics" }
vow-resolve = { path = "../vow-resolve" }

[dev-dependencies]
vow-lexer = { path = "../vow-lexer" }
vow-parser = { path = "../vow-parser" }

[lints]
workspace = true
